name: actions
run-name: ${{ github.actor }} dac actions 🚀
on:
  push:
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      run: |
        echo "Checked!"
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        version: ["3.11"]
    steps:
    - name: Test
      run: |
        echo "Tested!"
  release:
    runs-on: ubuntu-latest
    needs: [test, check-style]
    if: ${{ github.event_name == 'release' }}
    steps:
    - name: Release
      run: |
        echo "Released!"
  docs:
    runs-on: ubuntu-latest
    needs: [test, check-style]
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          echo "Docs!"
