name: actions
run-name: ${{ github.actor }} dac actions ${{ github.event_name }} ${{ github.ref }} 🚀
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      run: |
        echo "Checked!"
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        version: ["3.11"]
    steps:
    - name: Test
      run: |
        echo "Tested!"
  release:
    runs-on: ubuntu-latest
    needs: [test, check-style]
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
    - name: Release
      run: |
        echo "Released!"
  docs:
    runs-on: ubuntu-latest
    needs: [test, check-style]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          echo "Docs!"
